In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df.drop('Cabin',axis=1,inplace=True)

In [5]:
X = df.drop(['Survived','Name','Ticket'],axis=1).copy()
y = df['Survived'].copy()

In [6]:
num_imp = SimpleImputer(strategy = 'median')
cat_imp = SimpleImputer(strategy = 'most_frequent')
X['Age'] = num_imp.fit_transform(X[['Age']])
X['Embarked'] = cat_imp.fit_transform(X[['Embarked']]).ravel()

In [7]:
X = pd.get_dummies(X,columns= ['Sex','Embarked'],drop_first = True)

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [9]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
prediction = model.predict(X_test)
accuracy = accuracy_score(y_test,prediction)
print(f'Accuracy : {accuracy}')

Accuracy : 0.8435754189944135

In [10]:
result = permutation_importance(model,X_test,y_test,scoring = 'accuracy',n_repeats = 10,random_state = 42)
result_df = pd.DataFrame({
    'Features' : X.columns,
    'Importances' : result.importances_mean})
result_df

      Features  Importances
0  PassengerId     0.028492
1       Pclass     0.087709
2          Age     0.040223
3        SibSp     0.021229
4        Parch     0.018994
5         Fare     0.043017
6     Sex_male     0.187709
7   Embarked_Q     0.007821
8   Embarked_S     0.020112