In [107]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression 
from sklearn.linear_model import Lasso

In [108]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [109]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [110]:
df.drop('Cabin',axis=1,inplace = True)

In [111]:
num_imp = SimpleImputer(strategy = 'median')
cat_imp = SimpleImputer(strategy = 'most_frequent')
df['Age'] = num_imp.fit_transform(df[['Age']])
df['Embarked'] = cat_imp.fit_transform(df[['Embarked']]).ravel()

In [112]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [113]:
scaler = StandardScaler()
df['Fare'] = scaler.fit_transform(df[['Fare']])
df['Age'] = scaler.fit_transform(df[['Age']])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.565736,1,0,A/5 21171,-0.502445,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.663861,1,0,PC 17599,0.786845,C
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.258337,0,0,STON/O2. 3101282,-0.488854,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.433312,1,0,113803,0.420730,S
4,5,0,3,"Allen, Mr. William Henry",male,0.433312,0,0,373450,-0.486337,S

In [114]:
X = df.drop('Survived',axis=1)
y = df['Survived']

Dropping Name and Ticket as they Increase Irrelevant Features in Encoding

In [115]:
X.drop(['Name','Ticket'],axis=1,inplace = True)
X = pd.get_dummies(X)

In [116]:
X.head()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,3,-0.565736,1,0,-0.502445,False,True,False,False,True
1,2,1,0.663861,1,0,0.786845,True,False,True,False,False
2,3,3,-0.258337,0,0,-0.488854,True,False,False,False,True
3,4,1,0.433312,1,0,0.420730,True,False,False,False,True
4,5,3,0.433312,0,0,-0.486337,False,True,False,False,True

In [117]:
selector = SelectFromModel(LogisticRegression(l1_ratio=1,solver='saga',C = 0.05,max_iter = 10000))
X_selected = selector.fit_transform(X,y)

In [118]:
X_selected_df = pd.DataFrame(X_selected, columns = selector.get_feature_names_out())

In [119]:
X_selected_df.head()

   PassengerId  Pclass       Age  SibSp      Fare  Sex_female  Sex_male
0          1.0     3.0 -0.565736    1.0 -0.502445         0.0       1.0
1          2.0     1.0  0.663861    1.0  0.786845         1.0       0.0
2          3.0     3.0 -0.258337    0.0 -0.488854         1.0       0.0
3          4.0     1.0  0.433312    1.0  0.420730         1.0       0.0
4          5.0     3.0  0.433312    0.0 -0.486337         0.0       1.0