In [89]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import FunctionTransformer

In [90]:
df = pd.read_csv('train.csv')
df2 = pd.read_csv('Housing.csv')

USING TWO DATASETS FOR DIFFERENT PURPOSES
- FIRST - OUTLIERS
- SECOND - DATATYPE CORRECTIONS

In [91]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [92]:
df2

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.0,2,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

DETECTING OUTLIERS
- HERE THE OUTLIERS ARE GENUINE AS THEY REPRESENT INFORMATION (RICH CUSTOMERS)

In [93]:
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR
outliers = df[(df['Fare']<lower) | (df['Fare']>upper)]
print(outliers)

     PassengerId  Survived  Pclass  \
1              2         1       1
27            28         0       1
31            32         1       1
34            35         0       1
52            53         1       1
..           ...       ...     ...
846          847         0       3
849          850         1       1
856          857         1       1
863          864         0       3
879          880         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
27                      Fortune, Mr. Charles Alexander    male  19.0      3
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1
34                             Meyer, Mr. Edgar Joseph    male  28.0      1
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1
..                                                 ...     ...   ...    ...
846                           Sage, Mr. Douglas Bullen    male   NaN      8
849       Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  female   NaN      1
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.0      1
863                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN      8
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0

     Parch    Ticket      Fare        Cabin Embarked
1        0  PC 17599   71.2833          C85        C
27       2     19950  263.0000  C23 C25 C27        S
31       0  PC 17569  146.5208          B78        C
34       0  PC 17604   82.1708          NaN        C
52       0  PC 17572   76.7292          D33        C
..     ...       ...       ...          ...      ...
846      2  CA. 2343   69.5500          NaN        S
849      0     17453   89.1042          C92        C
856      1     36928  164.8667          NaN        S
863      2  CA. 2343   69.5500          NaN        S
879      1     11767   83.1583          C50        C

[116 rows x 12 columns]

- FUNCTION TRANSFORMER AND DATA TYPE CORRECTIONS

In [94]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

USING '.str.lower()' TO MAKE SURE THERE ARE NO INCONSISTENCIES

In [95]:
df2.columns = df2.columns.str.lower()
df2.columns = df2.columns.str.strip()

In [96]:
def date_decomp(X):
    X = X.copy()
    X['Year'] = X['date'].dt.year
    X['Month'] = X['date'].dt.month
    X['Day'] = X['date'].dt.day
    return X
def date_trans(X) :
    X = X.copy()
    X['date'] = pd.to_datetime(X['date'])
    return X
date_converter = FunctionTransformer(date_trans)
date_decomposer = FunctionTransformer(date_decomp)

In [97]:
from sklearn.pipeline import Pipeline
date_pipeline  = Pipeline([
    ('to_date',date_converter),
    ('date_decomp',date_decomposer)
])

In [98]:
print(df2['date'])

0        20141013T000000
1        20141209T000000
2        20150225T000000
3        20141209T000000
4        20150218T000000
              ...
21608    20140521T000000
21609    20150223T000000
21610    20140623T000000
21611    20150116T000000
21612    20141015T000000
Name: date, Length: 21613, dtype: str

In [99]:
df2 = date_pipeline.fit_transform(df2)
print(df2)

               id       date     price  bedrooms  bathrooms  sqft_living  \
0      7229300521 2014-10-13  231300.0         2       1.00         1180
1      6414100192 2014-12-09  538000.0         3       2.25         2570
2      5631500400 2015-02-25  180000.0         2       1.00          770
3      2487200875 2014-12-09  604000.0         4       3.00         1960
4      1954400510 2015-02-18  510000.0         3       2.00         1680
...           ...        ...       ...       ...        ...          ...
21608   263000018 2014-05-21  360000.0         3       2.50         1530
21609  6600060120 2015-02-23  400000.0         4       2.50         2310
21610  1523300141 2014-06-23  402101.0         2       0.75         1020
21611   291310100 2015-01-16  400000.0         3       2.50         1600
21612  1523300157 2014-10-15  325000.0         2       0.75         1020

       sqft_lot  floors  waterfront  view  ...  yr_built  yr_renovated  \
0          5650     1.0           0     0  ...      1955             0
1          7242     2.0           0     0  ...      1951          1991
2         10000     1.0           0     0  ...      1933             0
3          5000     1.0           0     0  ...      1965             0
4          8080     1.0           0     0  ...      1987             0
...         ...     ...         ...   ...  ...       ...           ...
21608      1131     3.0           0     0  ...      2009             0
21609      5813     2.0           0     0  ...      2014             0
21610      1350     2.0           0     0  ...      2009             0
21611      2388     2.0           0     0  ...      2004             0
21612      1076     2.0           0     0  ...      2008             0

       zipcode      lat     long  sqft_living15  sqft_lot15  Year  Month  Day
0        98178  47.5112 -122.257           1340        5650  2014     10   13
1        98125  47.7210 -122.319           1690        7639  2014     12    9
2        98028  47.7379 -122.233           2720        8062  2015      2   25
3        98136  47.5208 -122.393           1360        5000  2014     12    9
4        98074  47.6168 -122.045           1800        7503  2015      2   18
...        ...      ...      ...            ...         ...   ...    ...  ...
21608    98103  47.6993 -122.346           1530        1509  2014      5   21
21609    98146  47.5107 -122.362           1830        7200  2015      2   23
21610    98144  47.5944 -122.299           1020        2007  2014      6   23
21611    98027  47.5345 -122.069           1410        1287  2015      1   16
21612    98144  47.5941 -122.299           1020        1357  2014     10   15

[21613 rows x 24 columns]